---

- hosts: all
  become: true
  become_user: root

#  vars:
#    lb_server_address: 1.1.1.1 #Dummy var, will be set by vagrant script


# Python 2.7.15rc1 Available on default box
# Python 3.6.7  Available on default box

  tasks:
    - name: install pip
      apt:
        name: python-pip

    - name: install Flask
      pip:
        name: Flask

    - name: install gunicorn
      apt:
        name: gunicorn

    - name: install node
      apt:
        name: nodejs

    - name: install npm
      apt:
        name: npm

    - name: Also, let’s install build-essential package, which is needed for Node to work properly
      apt:
        name: build-essential

    - name: install React
      npm:
        name: create-react-app
        global: yes

    # Install firewall & configure
    # UFW already inslalled in source-box (default disabled)
    - name: Set ufw logging
      ufw:
        logging: on

    - name: Allow Incoming OpenSSH
      ufw:
        rule: allow
        name: OpenSSH
        direction: in

    - name: Allow Incoming port 22
      ufw:
        rule: allow
        port: 22
        direction: in
        state: enabled

    - name: Allow Incoming port 2222
      ufw:
        rule: allow
        port: 2222
        direction: in
        state: enabled

    - name: Allow Incoming www only from lb_server_address
      ufw:
        rule: allow
        port: 80
        direction: in
        #src: "{{lb_server_address}}"
        state: enabled

    - name: Allow all outgoing (Don't yet enable ufw)
      ufw:
        policy: allow
        direction: outgoing

    - name: Deny all incomming (enable ufw)
      ufw:
        state: enabled
        policy: deny
        direction: incoming
