---

- hosts: dbservers
  become: true
  become_user: root

  vars:
    BackendServers_subnet:
      - ip: 11.11.11.0/30   #Echte config wordt gepushed vanuit Vagrant, hebben we later nodig voor de fw rules
    username: _
    passwd: _

  tasks:

#############################
### User en ssh settings
############################

    #Create user
    - name: Creating user "{{username}}" with admin access
      user:
        name: "{{username}}"
        password: "{{ passwd | password_hash('sha512') }}"
        groups: adm
        append: yes
        shell: /bin/bash

    - name: Add user "{{username}}" to the sudoers
      copy:
        dest: "/etc/sudoers.d/{{username}}"
        content: "{{username}}  ALL=(ALL)  NOPASSWD: ALL"

    - name: Deploy SSH Key
      authorized_key: user={{username}}
                      key="{{ lookup('file', '/Users/{{username}}/.ssh/id_rsa.pub') }}"
                      state=present

    - name: Disable Password Authentication
      lineinfile:
           dest=/etc/ssh/sshd_config
           regexp='^PasswordAuthentication'
           line="PasswordAuthentication no"
           state=present
           backup=yes
    - name: Disable Root Login
      lineinfile:
           dest=/etc/ssh/sshd_config
           regexp='^PermitRootLogin'
           line="PermitRootLogin no"
           state=present
           backup=yes
      notify:
        - restart ssh


    #Install mysql server op standaard poort, met standaard configuratie
    - name: Install mysql
      apt: name=mysql-server state=present

    # Install firewall & configure
    # UFW reeds geinstalleerd op de source-box die we gebruiken (default disabled)
    - name: Set ufw logging
      ufw:
        logging: on

    - name: Allow Incoming OpenSSH
      ufw:
        rule: allow
        name: OpenSSH
        direction: in

    - name: Allow Incoming port 22
      ufw:
        rule: allow
        port: 22
        direction: in
        state: enabled

    - name: Allow Incoming port 2222
      ufw:
        rule: allow
        port: 2222
        direction: in
        state: enabled

    - name: Allow Incoming mysql from backend servers
      ufw:
        rule: allow
        port: 3306
        direction: in
        src: "{{BackendServers_subnet}}"
        state: enabled
        delete: yes

    - name: Allow Incoming mysql from backend servers
      ufw:
        rule: allow
        port: 3306
        direction: in
        #src: "{{BackendServers_subnet}}"
        state: enabled

    - name: Allow all outgoing (Don't yet enable ufw)
      ufw:
        policy: allow
        direction: outgoing

    - name: Deny all incomming (enable ufw)
      ufw:
        state: enabled
        policy: deny
        direction: incoming


  handlers:
    - name: restart ssh
      service:
          name: sshd
          state: restarted
