---

- hosts: dbservers
  become: true
  become_user: root

  vars:
    BackendServers_subnet:
      - ip: 11.11.11.0/30   #Echte config wordt gepushed vanuit Vagrant, hebben we later nodig voor de fw rules


  tasks:
    #Install mysql server op standaard poort, met standaard configuratie
    - name: Install mysql
      apt: name=mysql-server state=present

    # Install firewall & configure
    # UFW reeds geinstalleerd op de source-box die we gebruiken (default disabled)
    - name: Set ufw logging
      ufw:
        logging: on

    - name: Allow Incoming OpenSSH
      ufw:
        rule: allow
        name: OpenSSH
        direction: in

    - name: Allow Incoming port 22
      ufw:
        rule: allow
        port: 22
        direction: in
        state: enabled

    - name: Allow Incoming port 2222
      ufw:
        rule: allow
        port: 2222
        direction: in
        state: enabled

    - name: Allow Incoming mysql from backend servers
      ufw:
        rule: allow
        port: 3306
        direction: in
        src: "{{BackendServers_subnet}}"
        state: enabled

    - name: Allow all outgoing (Don't yet enable ufw)
      ufw:
        policy: allow
        direction: outgoing

    - name: Deny all incomming (enable ufw)
      ufw:
        state: enabled
        policy: deny
        direction: incoming
