---

- hosts: all
  become: true
  become_user: root

  vars:
    lb_server_address: 1.1.1.1 #Dummy var, will be set by vagrant script

  tasks:
    - name: Install nginx on frontend machine
      apt: name=nginx state=present

    # Install firewall $ configure
    # UFW already inslalled in source-box (default disabled)
    - name: Set ufw logging
      ufw:
        logging: on

    - name: Allow Incoming OpenSSH
      ufw:
        rule: allow
        name: OpenSSH
        direction: in

    - name: Allow Incoming port 22
      ufw:
        rule: allow
        port: 22
        direction: in
        state: enabled

    - name: Allow Incoming port 2222
      ufw:
        rule: allow
        port: 2222
        direction: in
        state: enabled

    - name: Allow Incoming www only from lb_server_address
      ufw:
        rule: allow
        port: 80
        direction: in
        src: "{{lb_server_address}}"
        state: enabled

    - name: Allow all outgoing (Don't yet enable ufw)
      ufw:
        policy: allow
        direction: outgoing

    - name: Deny all incomming (enable ufw)
      ufw:
        state: enabled
        policy: deny
        direction: incoming
