---

- hosts: lbservers
  become: true
  become_user: root

  vars:
#    haproxy_app_name: devopdsdops
    haproxy_mode: http
    haproxy_enable_stats: enable
    haproxy_algorithm: roundrobin
#    haproxy_backend_server:
#      name: _
#      ip: _
#      port: _
#      paramstring: _
    haproxy_backend_servers:
      - name: server1     #dummy structure, enkel ter voorbeels om aan te geven welke parameters er nodig zij
        ip: 11.11.11.11   #Echte config wordt gepushed vanuit Vagrant
        port: 80
        paramstring: cookie A check

    username: _
    passwd: _



  tasks:


#############################
### User en ssh settings
############################

    #Create user
    - name: Creating user "{{username}}" with admin access
      user:
        name: "{{username}}"
        password: "{{ passwd | password_hash('sha512') }}"
        groups: adm
        append: yes
        shell: /bin/bash

    - name: Add user "{{username}}" to the sudoers
      copy:
        dest: "/etc/sudoers.d/{{username}}"
        content: "{{username}}  ALL=(ALL)  NOPASSWD: ALL"

    - name: Deploy SSH Key
      authorized_key: user={{username}}
                      key="{{ lookup('file', '/Users/{{username}}/.ssh/id_rsa.pub') }}"
                      state=present

    - name: Disable Password Authentication
      lineinfile:
           dest=/etc/ssh/sshd_config
           regexp='^PasswordAuthentication'
           line="PasswordAuthentication no"
           state=present
           backup=yes
    - name: Disable Root Login
      lineinfile:
           dest=/etc/ssh/sshd_config
           regexp='^PermitRootLogin'
           line="PermitRootLogin no"
           state=present
           backup=yes
      notify:
        - restart ssh




    # Install firewall $ configure
    # UFW already inslalled in source-box (default disabled)
    - name: Set ufw logging
      ufw:
        logging: on

    - name: Allow Incoming OpenSSH
      ufw:
        rule: allow
        name: OpenSSH
        direction: in

    - name: Allow Incoming port 22
      ufw:
        rule: allow
        port: 22
        direction: in
        state: enabled

    - name: Allow Incoming port 2222
      ufw:
        rule: allow
        port: 2222
        direction: in
        state: enabled

    - name: Allow Incoming www (enable ufw)
      ufw:
        rule: allow
        port: 80
        direction: in

    - name: Allow all outgoing (Don't yet enable ufw)
      ufw:
        policy: allow
        direction: outgoing

    - name: Deny all incomming (Don't yet enable ufw)
      ufw:
        state: enabled
        policy: deny
        direction: incoming

    - name: Install HAProxy on loadbalancer
      apt: name=haproxy state=present

    - name: Update HAProxy config
      template: src=../cfg/lb_conf/haproxy.cfg
            dest=/etc/haproxy/haproxy.cfg
            backup=yes

    - name: Restart service HAProxy on loadbalancer, in all cases
      become: true
      become_user: root
      service:
        name: haproxy
        state: restarted


 
  handlers:
    - name: restart ssh
      service:
          name: sshd
          state: restarted
