---

- hosts: all

  vars:
#    haproxy_app_name: devopdsdops
    haproxy_mode: http
    haproxy_enable_stats: enable
    haproxy_algorithm: roundrobin
    haproxy_backend_servers:
      - {name: server1, ip: 10.133.181.247, port: 80, paramstring: cookie A check}
      - {name: server2, ip: 10.133.186.46, port: 80, paramstring: cookie A check}

  tasks:
    # Source box comes with nginx, needs to be disabled, and deinstalled
    - name: Stop nginx service
      become: true
      become_user: root
      service:
        name: nginx
        state: stopped

    - name: Deinstall nginx (haproxy needs to bind to port80 and nginx)
      become: true
      become_user: root
      apt: name=nginx state=absent

    - name: Install HAProxy on loadbalancer
      apt: name=haproxy state=present
      become: true
      become_user: root

#    - name: copy haproxy.cfg to loadbalancer
#      become: true
#      become_user: root
#      copy:
#        src: ../cfg/lb_conf/haproxy.cfg
#        dest: /etc/haproxy/haproxy.cfg
#        owner: root
#        group: root
#        mode: 0644

    - name: Update HAProxy config
      become: true
      become_user: root
      template: src=../cfg/lb_conf/haproxy.cfg
            dest=/etc/haproxy/haproxy.cfg
            backup=yes

    - name: Restart service HAProxy on loadbalancer, in all cases
      become: true
      become_user: root
      service:
        name: haproxy
        state: restarted
